version: '3.8'
# School Management System Docker Configuration
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_app
    restart: always
    working_dir: /var/www/html
    tty: true
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8080:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: school_db
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: school_phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=100M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: school_ngrok
    restart: unless-stopped
    command: http app:80 # Tunnel to the 'app' service on its internal port 80
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-2vOPFVzoXVjrLFw5Gpke52PxSF6_6MGjqkinLdPdLPmQvn74c}
    ports:
      - "4040:4040" # Expose Ngrok's web interface
    depends_on:
      - app
      
  redis:
    image: redis:alpine
    container_name: school_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  redis_data:

