apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: school-management-storage-pvc
  namespace: school-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
